"""
nano_inference/speculative.py

Implements Draft Model speculation and target model verification/rejection sampling.
"""

from typing import List, Tuple
import torch


class SpeculativeEngine:
    def __init__(self, k_speculative_tokens: int = 3):
        self.k = k_speculative_tokens

    def verify_and_accept(
        self,
        draft_tokens: List[int],
        target_logits: torch.Tensor,
        temperature: float = 0.7,
    ) -> List[int]:
        """
        Verifies draft candidate tokens using target model logits.
        Returns the accepted token sequence slice plus one corrected/next token.
        """
        accepted = []
        
        # Greedy verification check
        for i, draft_token in enumerate(draft_tokens):
            target_next_token = torch.argmax(target_logits[0, i, :], dim=-1).item()
            
            if draft_token == target_next_token:
                accepted.append(draft_token)
            else:
                # Rejection! Append target's corrected token and stop verifying candidate slice
                accepted.append(target_next_token)
                return accepted

        # If all K draft tokens passed, append the extra next token generated by target forward pass
        final_token = torch.argmax(target_logits[0, -1, :], dim=-1).item()
        accepted.append(final_token)
        return accepted